apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-keycloak
  labels:
    app: frontend-keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-keycloak
  template:
    metadata:
      labels:
        app: frontend-keycloak
    spec:
      containers:
      - name: frontend-keycloak
        image: ghcr.io/ryunchang/vue_crud_security_keycloak:master
        imagePullPolicy: Always
        env:
        - name: BACKEND_API_URL
          value: "backend-keycloak" 
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-keycloak
spec:
  selector:
    app: frontend-keycloak
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: front-duckdns-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
#  tls:
#  - hosts:
#    - frontend-keycloak-ssl-apps.kteducation.duckdns.org
#    secretName: edu-tls
#    # kubectl create secret tls edu-tls --cert /certs/wildcard-cert.pem --key /certs/wildcard-key.pem -n default
  rules:
  - host: frontend.yoonchang.duckdns.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-keycloak
            port:
              number: 80  
